### ISSUE TITLE
Add Ubuntu/Debian based container image as well

### ISSUE THREAD

**Issue by Lol3rrr** [itzg/rcon-cli#47]
In my use case I need to execute multiple commands over rcon, however I could not find a way to easily do that using the provided docker image (non interactive session). However because the image is based on "scratch" there is no support for running a bash script or something similar that then executes the cli multiple times one after another.

My idea would be to add a second container image that is not based on "scratch" but rather something like "ubuntu:22.04" or some debian variant, really anything that would allow for some extra things to be run, and then provide them as unter a tag like ":1.6.3-ubuntu" or similar

**Comment by itzg** [comment]
FYI, you can also send a multi-line string into stdin to execute multiple commands, but the approach in the PR was good too.
