### ISSUE TITLE
VIRUS FOUND VIRUSTOTAL

### ISSUE THREAD

**Issue by AntonyZI** [itzg/rcon-cli#54]
Just put the binary on VirusTotal

https://www.virustotal.com/gui/file/f945e1b2b17dfa73b569d57c02079a7282fe6ec00278c72ca009f93ecb3b2021

**Comment by itzg** [comment]
You're going to have to be a lot more specific about which version and which file you tested. I tested Windows and Linux amd64 builds from the [latest release 1.6.4](https://github.com/itzg/rcon-cli/releases/tag/1.6.4) and they were clean:

https://www.virustotal.com/gui/url/51610713015ec0ab448e478aa3cab255c8363facdd57974350fe201217b0edbf?nocache=1

https://www.virustotal.com/gui/url/f67898b90c1655016b540835a4e0f36c386577bc5f9b0b2d512cb4d8c47b5742?nocache=1

**Comment by AntonyZI** [comment]
I didn't put the tar.gz file, I put the executable directly

**Comment by itzg** [comment]
Thanks for clarifying. In that case I don't know why those three are flagging it. All the code is open source and the libraries are open source, so feel free to inspect it for any virus-y code if you're worried. Let me know what you find.

**Comment by itzg** [comment]
...I think I'll simply stop publishing Windows builds since the Linux build does not trigger any false negatives. All I need for the docker image is the Linux binary and I was only providing Windows binaries as a courtesy.

**Comment by itzg** [comment]
Windows builds are now discontinued as of

https://github.com/itzg/rcon-cli/releases/tag/1.6.5
