### ISSUE TITLE
Connection timed out, but server is perfectly accessible

### ISSUE THREAD

**Issue by MatteoInfi** [itzg/rcon-cli#7]
I keep getting this error: 

```
read tcp myIP:port->RCONserverIP:port: i/o timeout
```

Same configuration with RCON web client it works fine.

Is there a way to increase the timeout? **And does this work with Rust?**

**Comment by itzg** [comment]
I haven't actually tried it with Rust. Is that what you're connecting to?

**Comment by MatteoInfi** [comment]
@itzg Yes I am trying to connect to Rust.
Actually navigating thought your source code I have just realized that my problem might be with this package, `"github.com/james4k/rcon"` not the CLI itself
